export enum OperationType {
    DEPOSIT = "DEPOSIT",
    WITHDRAWAL = "WITHDRAWAL",
    TRANSFER_OUT = "TRANSFER_OUT",
    TRANSFER_IN = "TRANSFER_IN",
    EXCHANGE_OUT = "EXCHANGE_OUT",
    EXCHANGE_IN = "EXCHANGE_IN"
};